# Generated by Django 3.1.2 on 2020-10-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amphours',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='amphours',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='amphours',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
