# Generated by Django 3.1.2 on 2020-11-20 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_auto_20201017_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='kilowatthours',
            name='group',
        ),
        migrations.RemoveField(
            model_name='kilowatthours',
            name='location',
        ),
        migrations.RemoveField(
            model_name='kilowatthours',
            name='recorder_ptr',
        ),
        migrations.RemoveField(
            model_name='kilowatthours',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.DeleteModel(
            name='AmpHours',
        ),
        migrations.DeleteModel(
            name='KilowattHours',
        ),
        migrations.DeleteModel(
            name='Recorder',
        ),
        migrations.AddField(
            model_name='record',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.group'),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.location'),
        ),
        migrations.AddField(
            model_name='record',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder.unit'),
        ),
    ]
